<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Area', 'doctrine');

/**
 * BaseArea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $descripcion
 * @property boolean $inactivo
 * @property Doctrine_Collection $Movimientos
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getDescripcion() Returns the current record's "descripcion" value
 * @method boolean             getInactivo()    Returns the current record's "inactivo" value
 * @method Doctrine_Collection getMovimientos() Returns the current record's "Movimientos" collection
 * @method Area          setId()          Sets the current record's "id" value
 * @method Area          setDescripcion() Sets the current record's "descripcion" value
 * @method Area          setInactivo()    Sets the current record's "inactivo" value
 * @method Area          setMovimientos() Sets the current record's "Movimientos" collection
 * 
 * @package    ferro05
 * @subpackage model
 * @author     NMP
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArea extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Area');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('descripcion', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('inactivo', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'primary' => false,
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Movimiento as Movimientos', array(
             'local' => 'id',
             'foreign' => 'area_id'));
    }
}