<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SubtitulosxMov', 'doctrine');

/**
 * BaseSubtitulosxMov
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $movimiento_id
 * @property integer $subtitulo_id
 * @property Movimiento $Movimiento
 * @property Subtitulo $Subtitulo
 * 
 * @method integer        getMovimientoId()  Returns the current record's "movimiento_id" value
 * @method integer        getSubtituloId()   Returns the current record's "subtitulo_id" value
 * @method Movimiento     getMovimiento()    Returns the current record's "Movimiento" value
 * @method Subtitulo      getSubtitulo()     Returns the current record's "Subtitulo" value
 * @method SubtitulosxMov setMovimientoId()  Sets the current record's "movimiento_id" value
 * @method SubtitulosxMov setSubtituloId()   Sets the current record's "subtitulo_id" value
 * @method SubtitulosxMov setMovimiento()    Sets the current record's "Movimiento" value
 * @method SubtitulosxMov setSubtitulo()     Sets the current record's "Subtitulo" value
 * 
 * @package    ferro05
 * @subpackage model
 * @author     Matias Ezequiel Duarte
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSubtitulosxMov extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('SubtitulosxMov');
        $this->hasColumn('movimiento_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             ));
        $this->hasColumn('subtitulo_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Movimiento', array(
             'local' => 'movimiento_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Subtitulo', array(
             'local' => 'subtitulo_id',
             'foreign' => 'id'));
    }
}