<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Subtitulo', 'doctrine');

/**
 * BaseSubtitulo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $descripcion
 * @property integer $titulo_id
 * @property Titulo $Titulo
 * @property Doctrine_Collection $SubtitulosxMovs
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method string              getDescripcion()     Returns the current record's "descripcion" value
 * @method integer             getTituloId()        Returns the current record's "titulo_id" value
 * @method Titulo              getTitulo()          Returns the current record's "Titulo" value
 * @method Doctrine_Collection getSubtitulosxMovs() Returns the current record's "SubtitulosxMovs" collection
 * @method Subtitulo           setId()              Sets the current record's "id" value
 * @method Subtitulo           setDescripcion()     Sets the current record's "descripcion" value
 * @method Subtitulo           setTituloId()        Sets the current record's "titulo_id" value
 * @method Subtitulo           setTitulo()          Sets the current record's "Titulo" value
 * @method Subtitulo           setSubtitulosxMovs() Sets the current record's "SubtitulosxMovs" collection
 * 
 * @package    ferro05
 * @subpackage model
 * @author     Matias Ezequiel Duarte
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSubtitulo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Subtitulo');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('descripcion', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('titulo_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Titulo', array(
             'local' => 'titulo_id',
             'foreign' => 'id'));

        $this->hasMany('SubtitulosxMov as SubtitulosxMovs', array(
             'local' => 'id',
             'foreign' => 'subtitulo_id'));
    }
}