<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Folio_Otros', 'doctrine');

/**
 * BaseFolio_Otros
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $descripcion
 * @property Doctrine_Collection $Movimientos
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getDescripcion() Returns the current record's "descripcion" value
 * @method Doctrine_Collection getMovimientos() Returns the current record's "Movimientos" collection
 * @method Folio_Otros         setId()          Sets the current record's "id" value
 * @method Folio_Otros         setDescripcion() Sets the current record's "descripcion" value
 * @method Folio_Otros         setMovimientos() Sets the current record's "Movimientos" collection
 * 
 * @package    ferro05
 * @subpackage model
 * @author     Matias Ezequiel Duarte
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFolio_Otros extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Folio_Otros');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('descripcion', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Movimiento as Movimientos', array(
             'local' => 'id',
             'foreign' => 'folio_otros_id'));
    }
}