<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Movimiento', 'doctrine');

/**
 * BaseMovimiento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $usuario_id
 * @property integer $remitente_id
 * @property integer $responsable_id
 * @property integer $destinatario_id
 * @property datetime $fecha_recepcion
 * @property datetime $fecha_elevacion
 * @property integer $referencia_id
 * @property integer $area_id
 * @property integer $estado_id
 * @property string $tipo_doc
 * @property integer $referencia_nro
 * @property date $fecha_documento
 * @property boolean $cnrt_pendiente
 * @property boolean $tramite_pendiente
 * @property string $cudap
 * @property integer $cantidad_folios
 * @property string $comentarios
 * @property string $vinculo_exp
 * @property string $asunto
 * @property integer $folio_fep
 * @property integer $folio_nca
 * @property integer $folio_fsr
 * @property integer $folio_soe
 * @property integer $folio_allc
 * @property integer $folio_allm
 * @property integer $folio_sgld
 * @property integer $folio_otros_id
 * @property integer $nro_folio_otros
 * @property integer $cuerpo
 * @property Desti_Remi $Destinatario
 * @property Desti_Remi $Remitente
 * @property Responsable $Responsable
 * @property Referencia $Referencia
 * @property Area $Area
 * @property Estado $Estado
 * @property TipoDoc $TipoDoc
 * @property Folio_Otros $Folio_Otros
 * @property sfGuardUser $Usuario
 * @property Doctrine_Collection $SubtitulosxMovs
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method integer             getUsuarioId()       Returns the current record's "usuario_id" value
 * @method integer             getRemitenteId()     Returns the current record's "remitente_id" value
 * @method integer             getResponsableId()   Returns the current record's "responsable_id" value
 * @method integer             getDestinatarioId()  Returns the current record's "destinatario_id" value
 * @method datetime            getFechaRecepcion()  Returns the current record's "fecha_recepcion" value
 * @method datetime            getFechaElevacion()  Returns the current record's "fecha_elevacion" value
 * @method integer             getReferenciaId()    Returns the current record's "referencia_id" value
 * @method integer             getAreaId()    Returns the current record's "area_id" value
 * @method integer             getEstadoId()    Returns the current record's "estado_id" value
 * @method integer             getTipoDocId()    Returns the current record's "estado_id" value
 * @method integer             getReferenciaNro()   Returns the current record's "referencia_nro" value
 * @method date                getFechaDocumento()  Returns the current record's "fecha_documento" value
 * @method boolean             getCnrtPendiente()   Returns the current record's "cnrt_pendiente" value
 * @method boolean             getTramitePendiente() Returns the current record's "tramite_pendiente" value
 * @method string              getCudap()           Returns the current record's "cudap" value
 * @method integer             getCantidadFolios()  Returns the current record's "cantidad_folios" value
 * @method string              getComentarios()     Returns the current record's "comentarios" value
 * @method string              getVinculoExp()      Returns the current record's "vinculo_exp" value
 * @method string              getAsunto()          Returns the current record's "asunto" value
 * @method integer             getFolioFep()        Returns the current record's "folio_fep" value
 * @method integer             getFolioNca()        Returns the current record's "folio_nca" value
 * @method integer             getFolioFsr()        Returns the current record's "folio_fsr" value
 * @method integer             getFolioSoe()        Returns the current record's "folio_soe" value
 * @method integer             getFolioAllc()       Returns the current record's "folio_allc" value
 * @method integer             getFolioAllm()       Returns the current record's "folio_allm" value
 * @method integer             getFolioSgld()       Returns the current record's "folio_scld" value
 * @method integer             getFolioOtrosId()    Returns the current record's "folio_otros_id" value
 * @method integer             getNroFolioOtros()   Returns the current record's "nro_folio_otros" value
 * @method integer             getCuerpo()          Returns the current record's "cuerpo" value
 * @method Desti_Remi          getDestinatario()    Returns the current record's "Destinatario" value
 * @method Desti_Remi          getRemitente()       Returns the current record's "Remitente" value
 * @method Responsable         getResponsable()     Returns the current record's "Responsable" value
 * @method Referencia          getReferencia()      Returns the current record's "Referencia" value
 * @method Area          getArea()      Returns the current record's "Area" value
 * @method Estado          getEstado()      Returns the current record's "Estado" value
 * @method TipoDoc          getTipoDoc()      Returns the current record's "Estado" value
 * @method Folio_Otros         getFolioOtros()      Returns the current record's "Folio_Otros" value
 * @method sfGuardUser         getUsuario()         Returns the current record's "Usuario" value
 * @method Doctrine_Collection getSubtitulosxMovs() Returns the current record's "SubtitulosxMovs" collection
 * @method Movimiento          setId()              Sets the current record's "id" value
 * @method Movimiento          setUsuarioId()       Sets the current record's "usuario_id" value
 * @method Movimiento          setRemitenteId()     Sets the current record's "remitente_id" value
 * @method Movimiento          setResponsableId()   Sets the current record's "responsable_id" value
 * @method Movimiento          setDestinatarioId()  Sets the current record's "destinatario_id" value
 * @method Movimiento          setFechaRecepcion()  Sets the current record's "fecha_recepcion" value
 * @method Movimiento          setFechaElevacion()  Sets the current record's "fecha_elevacion" value
 * @method Movimiento          setReferenciaId()    Sets the current record's "referencia_id" value
 * @method Movimiento          setAreaId()    Sets the current record's "area_id" value
 * @method Movimiento          setEstadoId()    Sets the current record's "estado_id" value
 * @method Movimiento          setTipoDocId()    Sets the current record's "estado_id" value
 * @method Movimiento          setReferenciaNro()   Sets the current record's "referencia_nro" value
 * @method Movimiento          setFechaDocumento()  Sets the current record's "fecha_documento" value
 * @method Movimiento          setCnrtPendiente()   Sets the current record's "cnrt_pendiente" value
 * @method Movimiento          setTramitePendiente() Sets the current record's "tramite_pendiente" value
 * @method Movimiento          setCudap()           Sets the current record's "cudap" value
 * @method Movimiento          setCantidadFolios()  Sets the current record's "cantidad_folios" value
 * @method Movimiento          setComentarios()     Sets the current record's "comentarios" value
 * @method Movimiento          setVinculoExp()      Sets the current record's "vinculo_exp" value
 * @method Movimiento          setAsunto()          Sets the current record's "asunto" value
 * @method Movimiento          setFolioFep()        Sets the current record's "folio_fep" value
 * @method Movimiento          setFolioNca()        Sets the current record's "folio_nca" value
 * @method Movimiento          setFolioFsr()        Sets the current record's "folio_fsr" value
 * @method Movimiento          setFolioSoe()        Sets the current record's "folio_soe" value
 * @method Movimiento          setFolioAllc()       Sets the current record's "folio_allc" value
 * @method Movimiento          setFolioAllm()       Sets the current record's "folio_allm" value
 * @method Movimiento          setFolioSgld()       Sets the current record's "folio_scld" value
 * @method Movimiento          setFolioOtrosId()    Sets the current record's "folio_otros_id" value
 * @method Movimiento          setNroFolioOtros()   Sets the current record's "nro_folio_otros" value
 * @method Movimiento          setCuerpo()          Sets the current record's "cuerpo" value
 * @method Movimiento          setDestinatario()    Sets the current record's "Destinatario" value
 * @method Movimiento          setRemitente()       Sets the current record's "Remitente" value
 * @method Movimiento          setResponsable()     Sets the current record's "Responsable" value
 * @method Movimiento          setReferencia()      Sets the current record's "Referencia" value
 * @method Movimiento          setArea()      Sets the current record's "Area" value
 * @method Movimiento          setFolioOtros()      Sets the current record's "Folio_Otros" value
 * @method Movimiento          setUsuario()         Sets the current record's "Usuario" value
 * @method Movimiento          setSubtitulosxMovs() Sets the current record's "SubtitulosxMovs" collection
 * 
 * @package    ferro05
 * @subpackage model
 * @author     Matias Ezequiel Duarte
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMovimiento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Movimientos');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('usuario_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('remitente_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'unsigned' => true,
             'length' => 4,
             ));
        $this->hasColumn('responsable_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => true,
             'length' => 4,
             ));
        $this->hasColumn('destinatario_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'unsigned' => true,
             'length' => 4,
             ));
        $this->hasColumn('fecha_recepcion', 'datetime', null, array(
             'type' => 'datetime',
             'fixed' => 0,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('fecha_elevacion', 'datetime', null, array(
             'type' => 'datetime',
             'fixed' => 0,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('referencia_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'unsigned' => true,
             'length' => 4,
             ));
        $this->hasColumn('area_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'unsigned' => true,
             'length' => 4,
             ));
        $this->hasColumn('estado_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'unsigned' => true,
             'length' => 4,
             ));
        $this->hasColumn('referencia_nro', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_documento', 'date', null, array(
             'type' => 'date',
             'fixed' => 0,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('cnrt_pendiente', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'primary' => false,
             'notnull' => true,
             ));
        $this->hasColumn('tramite_pendiente', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'primary' => false,
             'notnull' => true,
             ));
        $this->hasColumn('cudap', 'string', 21, array(
             'type' => 'string',
             'fixed' => 0,
             'primary' => false,
             'notnull' => true,
             'length' => 21,
             ));
        $this->hasColumn('cantidad_folios', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('comentarios', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 500,
             ));
        $this->hasColumn('vinculo_exp', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('asunto', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 500,
             ));
        $this->hasColumn('folio_fep', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('folio_nca', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('folio_fsr', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('folio_soe', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('folio_allc', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('folio_allm', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('folio_sgld', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('folio_otros_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'unsigned' => true,
             'length' => 4,
             ));
        $this->hasColumn('nro_folio_otros', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('cuerpo', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Desti_Remi as Destinatario', array(
             'local' => 'destinatario_id',
             'foreign' => 'id'));

        $this->hasOne('Desti_Remi as Remitente', array(
             'local' => 'remitente_id',
             'foreign' => 'id'));

        $this->hasOne('Responsable', array(
             'local' => 'responsable_id',
             'foreign' => 'id'));

        $this->hasOne('Referencia', array(
             'local' => 'referencia_id',
             'foreign' => 'id'));
        $this->hasOne('Area', array(
             'local' => 'area_id',
             'foreign' => 'id'));
          $this->hasOne('Estado', array(
             'local' => 'estado_id',
             'foreign' => 'id'));
        $this->hasOne('Folio_Otros', array(
             'local' => 'folio_otros_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as Usuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id'));

        $this->hasMany('SubtitulosxMov as SubtitulosxMovs', array(
             'local' => 'id',
             'foreign' => 'movimiento_id'));
    }
}
