<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TitulosxMov', 'doctrine');

/**
 * BaseTitulosxMov
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $movimiento_id
 * @property integer $subtitulo_id
 * @property integer $titulo_id
 * @property Movimiento $Movimiento
 * @property Subtitulo $Subtitulo
 * @property Titulo $Titulo
 * 
 * @method integer     getMovimientoId()  Returns the current record's "movimiento_id" value
 * @method integer     getSubtituloId()   Returns the current record's "subtitulo_id" value
 * @method integer     getTituloId()      Returns the current record's "titulo_id" value
 * @method Movimiento  getMovimiento()    Returns the current record's "Movimiento" value
 * @method Subtitulo   getSubtitulo()     Returns the current record's "Subtitulo" value
 * @method Titulo      getTitulo()        Returns the current record's "Titulo" value
 * @method TitulosxMov setMovimientoId()  Sets the current record's "movimiento_id" value
 * @method TitulosxMov setSubtituloId()   Sets the current record's "subtitulo_id" value
 * @method TitulosxMov setTituloId()      Sets the current record's "titulo_id" value
 * @method TitulosxMov setMovimiento()    Sets the current record's "Movimiento" value
 * @method TitulosxMov setSubtitulo()     Sets the current record's "Subtitulo" value
 * @method TitulosxMov setTitulo()        Sets the current record's "Titulo" value
 * 
 * @package    ferro05
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTitulosxMov extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('TitulosxMov');
        $this->hasColumn('movimiento_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => true,
             ));
        $this->hasColumn('subtitulo_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => true,
             ));
        $this->hasColumn('titulo_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Movimiento', array(
             'local' => 'movimiento_id',
             'foreign' => 'id'));

        $this->hasOne('Subtitulo', array(
             'local' => 'subtitulo_id',
             'foreign' => 'id'));

        $this->hasOne('Titulo', array(
             'local' => 'titulo_id',
             'foreign' => 'id'));
    }
}