<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Titulo', 'doctrine');

/**
 * BaseTitulo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $descripcion
 * @property Doctrine_Collection $Subtitulos
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getDescripcion() Returns the current record's "descripcion" value
 * @method Doctrine_Collection getSubtitulos()  Returns the current record's "Subtitulos" collection
 * @method Titulo              setId()          Sets the current record's "id" value
 * @method Titulo              setDescripcion() Sets the current record's "descripcion" value
 * @method Titulo              setSubtitulos()  Sets the current record's "Subtitulos" collection
 * 
 * @package    ferro05
 * @subpackage model
 * @author     Matias Ezequiel Duarte
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTitulo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Titulo');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('descripcion', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Subtitulo as Subtitulos', array(
             'local' => 'id',
             'foreign' => 'titulo_id'));
    }
}