<?php

/**
 * AreaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ferro05
 * @subpackage model
 * @author     Nicolas Matias Piovano
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AreaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AreaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Area');
    }
}
   
