<?php

/**
 * Desti_RemiTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Desti_RemiTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Desti_RemiTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Desti_Remi');
    }
}