<?php

/**
 * Folio_OtrosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Folio_OtrosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Folio_OtrosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Folio_Otros');
    }
}