<?php

/**
 * MovimientoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MovimientoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MovimientoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Movimiento');       
    }   
    
}