<?php

/**
 * Movimiento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ferro05
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Movimiento extends BaseMovimiento
{
  public function __toString(){
    return $this->cudap;
  }
        
  public function save(Doctrine_Connection $conn = null)
  {
    if ($this->isNew())
    {
      $usuario=sfContext::getInstance()->getUser()->getGuardUser()->getId();    
      $this->setUsuarioId($usuario);
    }
 
    return parent::save($conn);
  }
  
  public static function getTitulosySubtitulos($movimiento)
  {   
     $Subtitulosresutls = Doctrine_Core::getTable('SubtitulosxMov')->findBy('movimiento_id', $movimiento->getId());
     $response="";
     if($Subtitulosresutls->count() > 0)    
        foreach ($Subtitulosresutls as $Subtitulosresutl){         
         $Subtitulo=$Subtitulosresutl->getSubtitulo();
         $Titulo=$Subtitulo->getTitulo();
         $response=$response."<p>".$Titulo." / ".$Subtitulo."</p></br>";        }
     
     return $response;     
  } 
  public static function getTitulosySubtitulosRaw($movimiento)
  {   
     $Subtitulosresutls = Doctrine_Core::getTable('SubtitulosxMov')->findBy('movimiento_id', $movimiento->getId());
     $response="";
     if($Subtitulosresutls->count() > 0)    
        foreach ($Subtitulosresutls as $Subtitulosresutl){         
         $Subtitulo=$Subtitulosresutl->getSubtitulo();
         $Titulo=$Subtitulo->getTitulo();
         $response=$response.$Titulo." / ".$Subtitulo.", ";        }
     
     return $response;     
  } 
}
