<?php

/**
 * ReferenciaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReferenciaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReferenciaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Referencia');
    }
}