<?php

/**
 * Referencia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ferro05
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Referencia extends BaseReferencia
{
	public function __toString(){
            if(is_string($this->descripcion))
		return $this->descripcion;
            else
                return '';
	}
        
        public function save(Doctrine_Connection $conn = null)
        {
            if ($this->isNew())
            {    
                $this->setInactivo(false);
            }
 
        return parent::save($conn);
        }
}
