<?php

/**
 * ResponsableTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ResponsableTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ResponsableTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Responsable');
    }
}