<?php

/**
 * SubtitulosxMovTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubtitulosxMovTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SubtitulosxMovTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SubtitulosxMov');
    }
}