<?php

/**
 * SubtituloTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubtituloTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SubtituloTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Subtitulo');
    }
}